# Generated by Django 4.2.2 on 2023-06-29 10:17

from django.db import migrations, models
import django.db.models.deletion
import pfapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Traits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.JSONField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heritages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.JSONField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfapi.sources')),
            ],
        ),
        migrations.CreateModel(
            name='Feats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.JSONField(blank=True, null=True)),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('level', models.IntegerField()),
                ('sources', models.ManyToManyField(blank=True, to='pfapi.sources')),
                ('traits', models.ManyToManyField(to='pfapi.traits')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfapi.feattypes')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.JSONField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pfapi.sources')),
            ],
        ),
        migrations.CreateModel(
            name='Ancestries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.JSONField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('abilities', models.JSONField(default=pfapi.models.jsonAncestryAbilities)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pfapi.sources')),
            ],
        ),
    ]
