# Generated by Django 4.2.2 on 2023-07-01 12:19

from django.db import migrations, models
import pfapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pfapi', '0003_alter_classes_abilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backgrounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.JSONField(blank=True, null=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('abilities', models.JSONField(default=pfapi.models.jsonAncestryAbilities)),
            ],
        ),
    ]
